/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Produto;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import model.ProdutoDAO;

public class ProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public ProdutoView() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        produtosJTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        opcaoProdutoComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nomeProdutoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precoProdutoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantidadeProdutoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        marcaEletronicoTextField = new javax.swing.JTextField();
        modeloEletronicoTextField = new javax.swing.JTextField();
        validadeAlimentoTextField = new javax.swing.JTextField();
        adicionarProdutoButton = new javax.swing.JButton();
        removerProdutoButton = new javax.swing.JButton();
        editarProdutoButton = new javax.swing.JButton();
        listarOrdenadoProdutosButton = new javax.swing.JButton();
        listarNaoOrdenadoProdutosButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Produtos");

        produtosJTextArea.setEditable(false);
        produtosJTextArea.setColumns(20);
        produtosJTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        produtosJTextArea.setRows(5);
        jScrollPane1.setViewportView(produtosJTextArea);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de Produto:");

        opcaoProdutoComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opcaoProdutoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimento", "Eletrônico" }));
        opcaoProdutoComboBox.setPreferredSize(new java.awt.Dimension(72, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        nomeProdutoTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeProdutoTextField.setMinimumSize(new java.awt.Dimension(64, 28));
        nomeProdutoTextField.setPreferredSize(new java.awt.Dimension(79, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Preço:");

        precoProdutoTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        precoProdutoTextField.setPreferredSize(new java.awt.Dimension(79, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade:");

        quantidadeProdutoTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantidadeProdutoTextField.setPreferredSize(new java.awt.Dimension(79, 28));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Marca (para Eletrônicos):");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Modelo (para Eletrônicos):");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Data de Validade (para Alimentos):");

        marcaEletronicoTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        marcaEletronicoTextField.setPreferredSize(new java.awt.Dimension(79, 28));

        modeloEletronicoTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modeloEletronicoTextField.setPreferredSize(new java.awt.Dimension(79, 28));

        validadeAlimentoTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        validadeAlimentoTextField.setPreferredSize(new java.awt.Dimension(79, 28));

        adicionarProdutoButton.setText("Adicionar Produto");

        removerProdutoButton.setText("Remover Produto");

        editarProdutoButton.setText("Editar Produto");

        listarOrdenadoProdutosButton.setText("Listar Produtos Ordenados");

        listarNaoOrdenadoProdutosButton.setText("Listar Produtos Não Ordenados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opcaoProdutoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeProdutoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(precoProdutoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantidadeProdutoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(marcaEletronicoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modeloEletronicoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(validadeAlimentoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listarOrdenadoProdutosButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarNaoOrdenadoProdutosButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adicionarProdutoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerProdutoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarProdutoButton)))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(opcaoProdutoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precoProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quantidadeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(marcaEletronicoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(modeloEletronicoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(validadeAlimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarProdutoButton)
                    .addComponent(removerProdutoButton)
                    .addComponent(editarProdutoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarOrdenadoProdutosButton)
                    .addComponent(listarNaoOrdenadoProdutosButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoView().setVisible(true);
            }
        });
    }
    
    public JButton getAdicionarProdutoButton(){
        return adicionarProdutoButton;
    }
    
    public JButton getRemoverProdutoButton(){
        return removerProdutoButton;
    }

    public JButton getEditarProdutoButton(){
        return editarProdutoButton;
    }
    
    public JButton getListarOrdenadoProdutosButton(){
        return listarOrdenadoProdutosButton;
    } 

    public JButton getListarNaoOrdenadoProdutosButton(){
        return listarNaoOrdenadoProdutosButton;
    }  
    
    public JComboBox getOpcaoComboBox(){
        return opcaoProdutoComboBox;
    }
    
    public JTextField getNomeProdutoTextField(){
        return nomeProdutoTextField;
    }
    
    public JTextField getPrecoProdutoTextField(){
        return precoProdutoTextField;
    }
    
    public JTextField getQuantidadeProdutoTextField(){
        return quantidadeProdutoTextField;
    }
    
    public JTextField getMarcaEletronicoTextField(){
        return marcaEletronicoTextField;
    }
    
    public JTextField getModeloEletronicoTextField(){
        return modeloEletronicoTextField;
    }  
    
    public JTextField getValidadeAlimentoTextField(){
        return validadeAlimentoTextField;
    }
   
    /* Atualiza 'produtosJTextArea' com a lista de produtos do ProdutoDAO. Limpa o campo de texto e adiciona cada produto da lista formatado por 'toString()' em uma nova linha. */
    public void setProdutosJTextArea(ProdutoDAO produtos) {
        produtosJTextArea.setText(""); 
        for (Produto produto : produtos.getListaProdutos()) {
            produtosJTextArea.append(produto.toString() + "\n");
        }
    }
    
    public void setNomeProdutoTextField(){
        nomeProdutoTextField.setText("");
    }
    
    public void setPrecoProdutoTextField(){
        precoProdutoTextField.setText("");
    }
    
    public void setQuantidadeProdutoTextField(){
        quantidadeProdutoTextField.setText("");
    }
    
    public void setValidadeAlimentoTextField(){
        validadeAlimentoTextField.setText("");
    }
    
    public void setModeloEletronicoTextField() {
        modeloEletronicoTextField.setText("");
    }
    
    public void setMarcaEletronicoTextField() {
        marcaEletronicoTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarProdutoButton;
    private javax.swing.JButton editarProdutoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarNaoOrdenadoProdutosButton;
    private javax.swing.JButton listarOrdenadoProdutosButton;
    private javax.swing.JTextField marcaEletronicoTextField;
    private javax.swing.JTextField modeloEletronicoTextField;
    private javax.swing.JTextField nomeProdutoTextField;
    private javax.swing.JComboBox<String> opcaoProdutoComboBox;
    private javax.swing.JTextField precoProdutoTextField;
    private javax.swing.JTextArea produtosJTextArea;
    private javax.swing.JTextField quantidadeProdutoTextField;
    private javax.swing.JButton removerProdutoButton;
    private javax.swing.JTextField validadeAlimentoTextField;
    // End of variables declaration//GEN-END:variables

}
